name: AutoFormatSQL

on:
  push:
    branches:
      - master
    paths:
      - "**.sql"

jobs:
  trim_whitespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: "10"

      - name: Trim trailing whitespace and replace Tabs
        shell: pwsh
        run: |
          $changedFiles = git --no-pager diff --name-only --relative  --diff-filter=AM "${{ github.event.before }}" "${{ github.sha }}" -- '***.sql'
          $tabSize = 4
          $outputString = ""
          $changedFiles | ForEach-Object {
            $fullPath = $_
            $Content = Get-Content $fullPath
            foreach ($Ctnt in $Content) {
              $CharArray = $Ctnt.ToCharArray()
              $lineOutput = ""
              $slidingOffset = 0
              for ($charIdx = 0; $charIdx -lt $CharArray.Length; $charIdx++) {
                  if ($CharArray[$charIdx] -eq "`t") {
                      $currentTab = $tabSize - (($charIdx + $slidingOffset) % $tabSize)
                      $slidingOffset += $currentTab - 1
                      $lineOutput += (" " * $currentTab) 
                  }
                  else {
                      $lineOutput += $CharArray[$charIdx] 
                  }
              }
              $outputString += $lineOutput.TrimEnd() + "`n"   # Add line output with trailing spaces removed to the output string, and add newline
            }
            Set-Content -Path $fullPath -Value ($outputString.TrimEnd())
          }
      - name: Commit changes
        # requries Settings\Actions\General\Workflow permissions\Read and write permissions
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Update files"
            git remote set-url origin "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
            git push origin HEAD:${{ github.ref }}
          fi
